# Taken from: https://medium.com/@shakyShane/lets-talk-about-docker-artifacts-27454560384f

# Stage 1 - the build process
FROM node:10 as build-deps
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm i
COPY . ./
RUN npm run build

# Stage 2 - the production environment
FROM nginx:alpine
COPY --from=build-deps /usr/src/app/build /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
