export default {
  CLEAR: 'bucket/CLEAR',
  API_CALL: 'bucket/API_CALL',
  START_CALL: 'bucket/START_CALL',
  END_CALL: 'bucket/END_CALL',
  UPDATE_COUNTRIES: 'bucket/UPDATE_COUNTRIES',
  SELECT_COUNTRY: 'bucket/SELECT_COUNTRY',
  UPDATE_CITIES: 'bucket/UPDATE_CITIES',
  SELECT_CITY: 'bucket/SELECT_CITY',
  REMOVE_CITY: 'bucket/REMOVE_CITY',
  UPDATE_BUDGET: 'bucket/UPDATE_BUDGET',
};
